apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- clusterrole.yaml
- clusterrolebinding.yaml
- prometheus.yaml
- psp-clusterrole.yaml
- psp-clusterrolebinding.yaml
- psp.yaml
- service.yaml
- serviceaccount.yaml
- servicemonitor.yaml
