---
# Source: prometheus-operator/templates/prometheus/psp-clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-basic-psp
  labels:
    app: prometheus-basic
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-basic
subjects:
  - kind: ServiceAccount
    name: prometheus-basic
    namespace: monitoring
