---
# Source: prometheus-operator/templates/prometheus/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: prometheus-basic
  labels:
    app: prometheus-basic
    self-monitor: "true"
spec:
  ports:
  - name: web
    port: 9090
    targetPort: 9090
  selector:
    app: prometheus-basic
    prometheus: prometheus-basic
  type: "ClusterIP"
