---
# Source: prometheus-operator/templates/prometheus/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-basic
  labels:
    app: prometheus-basic
spec:
  selector:
    matchLabels:
      app: prometheus-basic
      self-monitor: "true"
  namespaceSelector:
    matchNames:
      - "monitoring"
  endpoints:
  - port: web
    path: "/metrics"
