apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: "prometheus-operator"
resources:
- namespace.yaml
- admission-webhooks/mutatingWebhookConfiguration.yaml
- admission-webhooks/validatingWebhookConfiguration.yaml
- clusterrole.yaml
- clusterrolebinding.yaml
- deployment.yaml
- psp-clusterrole.yaml
- psp-clusterrolebinding.yaml
- psp.yaml
- service.yaml
- serviceaccount.yaml
- servicemonitor.yaml