---
# Source: prometheus-operator/templates/prometheus-operator/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: prometheus-operator
  labels:
    app: prometheus-operator
spec:
  ports:
  - name: http
    port: 8080
    targetPort: http
  selector:
    app: prometheus-operator
  type: "ClusterIP"
